server:
	application:
		name: "gatewayserver"
	config:
		import: "optional:configserver:http://localhost:8071/"
	cloud:
		gateway:
			discovery:
				locator:
					enabled: true
			
management:
	endpoints:
		web:
			exposure:
				include: "*"
	endpoint:
		dateway:
			enabled: true
	info:
		env:
			enabled: true
info:
	app:
		name: "gatewayserver"
		description: "Gateway Server"
		varsion: "1.0.0"