services:
  rabbit:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  configserver:
    image: "rupam/configserver:v1"
#    image: "javaBank/configserver:v1"
    container_name: "configserver-ms"
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:8071/actuator/health/readiness"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 500m
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "rupam/accounts:v1"
#    image: "javaBank/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          memory: 500m
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "rupam/loanapplication:v1"
#    image: "javaBank/loans:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          memory: 500m
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  creditcard:
    image: "rupam/creditcard:v1"
#    image: "javaBank/creditcard:v1"
    container_name: creditcard-ms
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          memory: 500m
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  javams:
    driver: bridge
