services:
  rabbit:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  configserver:
    image: "javaBank/configserver:v1"
    container_name: "configserver-ms"
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_completed_successfully
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 500m
    extends:
     file: common-config.yml
     service: network-deploy-service

  accounts:
    image: "javaBank/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      extends:
        file: common-config.yml
        service: microservice-configserver-config
    depends_on:
      configserver:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      -javams
#    environment:
#      SPRING_APPLICATION_NAME: "accounts"
#      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
#      SPRING_PROFILES_ACTIVE: default

  loans:
    image: "javaBank/loans:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      -javams
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: default

  creditcard:
    image: "javaBank/creditcard:v1"
    container_name: creditCard
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICTION_NAME: "credicards"
#    depends_on:
#      configserver:
#        condition: service_completed_successfully
#    deploy:
#      resources:
#        limits:
#          memory: 500m
    networks:
      -javams
    environment:
      SPRING_APPLICATION_NAME: "creditcard"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: default
networks:
  javams:
    driver: "bridge"