services:
  configserver:
    image: "javaBank/configserver:v1"
    container_name: "configserver-ms"
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      -javams
  accounts:
    image: "javaBank/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      -javams
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: default
  loans:
    image: "javaBank/loans:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      -javams
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: default
  creditcard:
    image: "javaBank/creditcard:v1"
    container_name: creditCard
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      -javams
    environment:
      SPRING_APPLICATION_NAME: "creditcard"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: default
networks:
  javams:
    driver: "bridge"