server:
  http_listen_port: 3100

distributor:
  receivers:
    otlp:
      protocols:
        http:
        grpc:
#    jaeger:
#      protocols:
#        thrift_http:
#        grpc:

ingester:
  trace_idle_period: 10s
  max_block_bytes: 1_000_000
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 1h
    compaction_window: 1h
    max_compaction_objects: 1000000
    compacted_block_retention: 10m

#storage:
#  trace:
#    backend: local
#    local:
#      path: /tmp/tempo/traces
#    wal:
#      path: /tmp/tempo/wal
