server:
  port: 8071

spring:
  profiles:
#    active: native  --this is added if files needed to be added from files
    active: "git"

  cloud:
    config:
      server:
#        native:
#          search-locations: classpath:/config/, file:///F:/Development/java\java-bank-microservice\springClouds/config-files
        git:
          uri: "https://github.com/rupamswain1/java-bank-microservice.git"
          default-label: main
          timeout: 5
          search-paths: springClouds/src/main/resources/config
          clone-on-start: true
          force-pull: true
encrypt:
  key: "thisIsADemoKeyToTestEncryption"