server:
  port: 8071

spring:
  profiles:
#    active: native
    active: "git"

  cloud:
    config:
      server:
#        native:
#          search-locations: classpath:/config/, file:///F:/Development/java\java-bank-microservice\springClouds/config-files
        git:
          uri: "https://github.com/rupamswain1/java-bank-microservice.git"
          default-label: main
          timeout: 5
          search-paths: springClouds/src/main/resources/config
          clone-on-start: true
          force-pull: true

encrypt:
  key: "thisIsADemoKeyToTestEncryption"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  #micromeeter configuration
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  level:
    in:
      rupam:
        springClouds: DEBUG
  pattern:
    level: "%5p[${spring.application.name},%X{trace_id},%X{span_id}]"