server:
  port: "9000"

spring:
  application:
    name: "creditCards"
  profiles:
    active: "qa"
  datasource:
    url: "jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:6543/postgres?user=postgres.glrzfqcaggzwfnscvitg&password=J@nu@rryRup@m"
    username: "postgres.glrzfqcaggzwfnscvitgp"
    password: "J@nu@rryRup@m"
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      data-source-properties:
        cachePrepStmts: false
  jpa:
    hibernate:
      ddl.auto: "update"
      show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071"


rabbitmq:
  host: "localhost"
  port: 5672
  username: "guest"
  password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"