server:
  port: "9000"

spring:
  application:
    name: "creditCards"
  profiles:
    active: "qa"
  datasource:
    url:
    username:
    password:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      data-source-properties:
        cachePrepStmts: false
  jpa:
    hibernate:
      ddl.auto: "update"
      show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071"

management:
  endpoints:
    web:
      exposure:
        include: "*"
