server:
  port: "9000"

spring:
  application:
    name: "creditCards"
  profiles:
    active: "default"
  datasource:
    url: ""
    username: ""
    password: ""
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      data-source-properties:
        cachePrepStmts: false
  jpa:
    hibernate:
      ddl.auto: "update"
      show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071"

#
#rabbitmq:
#  host: "localhost"
#  port: 5672
#  username: "guest"
#  password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    enable:
      shutdown: true
    info:
      env:
        access: unrestricted
endpoints:
  shutdown:
    enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "creditcards"
    description: "creditcard Application"
    version: "1.0.1"